apiVersion: v1
kind: Secret
metadata:
  name: {{ include "database-chart.fullname" . }}-secret
type: Opaque
stringData:
  dbRootPassword: {{ .Values.secrets.rootPassword | quote }}
  dbUsername: {{ .Values.secrets.username | quote }}
  dbPassword: {{ .Values.secrets.password | quote }}
  dbName: {{ .Values.secrets.database | quote }}
