replicaCount: 1

image:
  repository: toannd135/shoeshop-database
  pullPolicy: Always
  tag: "v1.1.1"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""  
resources: {}


service:
  name: shoeshop-mysql
  type: ClusterIP
  port: 3306

secrets:
  username: "dbshoeshop"
  rootPassword: "123456"
  database: shoeshop
  password : "123456"

persistence:
  size: 1Gi
  storageClassName: "standard" 